name: eliud_pkg_apps
description: Eliud package with generation of app contents
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  #flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals

  eliud_pkg_shop:
    path: ../eliud_pkg_shop

  eliud_pkg_feed:
    path: ../eliud_pkg_feed

  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_pay:
    path: ../eliud_pkg_pay

  eliud_pkg_post:
    path: ../eliud_pkg_post

  eliud_pkg_album:
    path: ../eliud_pkg_album

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/eliud_pkg_apps/assets/eliud_app/logos/logo.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/logos/logo_head.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/devices/android.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/devices/iphone.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/devices/macbook.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/devices/tablet.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app4.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app5.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app6.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-android-app7.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-authentication1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-authentication2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-database1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-database2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-database3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project4.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project5.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-firebase-project6.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-flutter-project1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-flutter-project2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-flutter-project3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-flutter-project4.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-flutter-webproject3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-google-account1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-google-account2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-google-account3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-google-account4.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-google-account5.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-storage1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-storage2.png
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-storage3.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-storage4.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/create-webapp2.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/deploy-webapp1.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/tutorials/firebase-home.jpg
    - packages/eliud_pkg_apps/assets/eliud_app/legal/privacy-policy.html
    - packages/eliud_pkg_apps/assets/eliud_app/legal/terms-of-service.html
    - packages/eliud_pkg_apps/assets/eliud_app/legal/disclaimer.html
    - packages/eliud_pkg_apps/assets/minkey_app/logos/logo.png
    - packages/eliud_pkg_apps/assets/minkey_app/logos/logo_head.png
    - packages/eliud_pkg_apps/assets/minkey_app/feed/example_photo1.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/feed/example_photo2.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/feed/example_photo3.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/feed/example_video1.mp4
    - packages/eliud_pkg_apps/assets/minkey_app/devices/android.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/devices/iphone.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/devices/macbook.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/devices/tablet.jpg
    - packages/eliud_pkg_apps/assets/minkey_app/legal/privacy-policy.html
    - packages/eliud_pkg_apps/assets/minkey_app/legal/terms-of-service.html
    - packages/eliud_pkg_apps/assets/minkey_app/legal/disclaimer.html
    - packages/eliud_pkg_apps/assets/incidamus_app/logos/logo.png
    - packages/eliud_pkg_apps/assets/incidamus_app/logos/logo_head.png
    - packages/eliud_pkg_apps/assets/incidamus_app/feed/example_photo1.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/feed/example_photo2.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/feed/example_photo3.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/feed/example_video1.mp4
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/face1.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/face2.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/face3.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/face4.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/body1.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/body2.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/body3.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/body3b.png
    - packages/eliud_pkg_apps/assets/incidamus_app/decorating/body4.png
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/1.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/2.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/3.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/4.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/5.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/6.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/7.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/8.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/9.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/10.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/11.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/12.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/13.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/14.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/15.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/16.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/17.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/18.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/19.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/20.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/21.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/22.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/23.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/24.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/25.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/26.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/27.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/28.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/29.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/30.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/31.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/32.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/33.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/34.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/35.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/36.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/37.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/38.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/39.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/40.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/41.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/42.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/43.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/44.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/45.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/46.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/47.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/48.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/49.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/50.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/51.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/52.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/53.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/54.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/55.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/56.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/57.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/58.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/59.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/60.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/61.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/62.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/63.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/photos/64.jpg
    - packages/eliud_pkg_apps/assets/incidamus_app/products/blackandwhite1.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/blackandwhite2.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/blackandwhite3.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/blackandwhite4.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/sludge1.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/govno1.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/products/blackandwhitecar1.webp
    - packages/eliud_pkg_apps/assets/incidamus_app/legal/privacy-policy.html
    - packages/eliud_pkg_apps/assets/incidamus_app/legal/terms-of-service.html
    - packages/eliud_pkg_apps/assets/incidamus_app/legal/disclaimer.html
    - packages/eliud_pkg_apps/assets/juuwle_app/logos/logo.png
    - packages/eliud_pkg_apps/assets/juuwle_app/logos/logo_head.jpg
    - packages/eliud_pkg_apps/assets/shared/about/thocha.png
    - packages/eliud_pkg_apps/assets/shared/blocked/blocked.png
    - packages/eliud_pkg_apps/assets/juuwle_app/decorating/charlotte_sitting.png
    - packages/eliud_pkg_apps/assets/juuwle_app/decorating/charlotte_standing.png
    - packages/eliud_pkg_apps/assets/juuwle_app/decorating/charlotte_with_credit_card.png
    - packages/eliud_pkg_apps/assets/juuwle_app/decorating/charlotte_presenting.png
    - packages/eliud_pkg_apps/assets/juuwle_app/decorating/charlotte_with_bags.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/gouldianfinch1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/gouldianfinch2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/redbreastedblackbird1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/redbreastedblackbird2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/queenofthenight1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/queenofthenight2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/goldenoriole1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/goldenoriole2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/turquoisekakariki1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/turquoisekakariki2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/amaryllis1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/amaryllis2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/daisy1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/daisy2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/anemone1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/anemone2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/lilyofthenile1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/lilyofthenile2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/bluebackedmanakin1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/bluebackedmanakin2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/northerncardinal1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/northerncardinal2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/eurasianmagpie1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/eurasianmagpie2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/myna1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/myna2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/parakeet1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/parakeet2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/kingbird1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/kingbird2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/grosbeak1.png
    - packages/eliud_pkg_apps/assets/juuwle_app/products/grosbeak2.png
    - packages/eliud_pkg_apps/assets/juuwle_app/legal/privacy-policy.html
    - packages/eliud_pkg_apps/assets/juuwle_app/legal/terms-of-service.html
    - packages/eliud_pkg_apps/assets/juuwle_app/legal/disclaimer.html
