name: eliud_pkg_apps
description: Eliud package with generation of app contents
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals

  eliud_pkg_shop:
    path: ../eliud_pkg_shop

  eliud_pkg_feed:
    path: ../eliud_pkg_feed

  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_follow:
    path: ../eliud_pkg_follow

  eliud_pkg_membership:
    path: ../eliud_pkg_membership

  eliud_pkg_pay:
    path: ../eliud_pkg_pay

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
